### ISSUE TITLE
Wrong received type get from module

### ISSUE THREAD

**Issue by Revilo91** [klein0r/ioBroker.comfoairq#12]
**Describe the bug**  
In log files this error appears periodically:
State value to set for "comfoairq.0.sensor.******" has to be type "string" but received type "number"

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/39066472/123627151-f4522580-d811-11eb-9a63-22923b7ae814.png)

**Versions:**  
 - Adapter version: 0.0.4
 - JS-Controller version: 3.3.14
 - Node version: v12.22.1
 - Operating system: Docker for Synology (buanet/iobroker:latest)

**Comment by Streit187** [comment]
Just change the type or change the log level of the adapter.

**Comment by jookeer** [comment]
I have the same issue.
- Adapter version: 0.0.4
- Node version: v12.20.2
- Operating system: Raspberry pi

**Comment by klein0r** [comment]
1. Update adapter to 0.1.0 (or later)
2. Stop the instance
3. Delete all objects of `comfoairq.0`
4. Start the instance
