### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by Snapergy** [klein0r/ioBroker.comfoairq#17]
### The problem

Hallo zusammen,

ich nutze IoBroker in Docker im Bridge-Modus. Leider funktionieren hierbei keine UPNP-Requests, sodass ich über die beschriebene Lösung nicht an die UUID herankomme. Gibt es eine andere Möglichkeit diese herauszufinden? Würde den Adapter mit seinen Möglichkeiten schon gerne nutzen, aber leider klappt das ohne UUID nicht...

### Version of ioBroker js-controller

3.3.15

### Version of Adapter

0.0.4

### Operating system running ioBroker

Linux (Docker)

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Du könntest lokal die Discovery mit dem Test-Script anstoßen. Bitte hier eigenständig einlesen:

https://github.com/klein0r/node-comfoairq

**Comment by Snapergy** [comment]
Danke, hatte es dann alleine irgendwie mit nem selbst geschriebenen Skript hinbekommen. Wäre natürlich von Vorteil, wenn es so ein Skript inkl. Anleitung einfach mit dem Adapter gibt, sodass es wesentlich einfacher für die User ist, an die UUID zu kommen.

**Comment by klein0r** [comment]
Du kannst das Script ja gerne teilen, dann kann ich das mit verlinken. Hast es ja schon fertig

**Comment by Snapergy** [comment]
Fertig ist gut :D

Ich habe mein vorher genutzt pycomfoconnect Skript angepasst, sodass es mir auf der Console die UUID ausgibt. Bin jetzt nicht der Python-Pro, deswegen ist in dem Skript noch viel drin, was wahrscheinlich nicht rein muss. Eventuell kannst du es ja noch einkürzen.
[getuuid.txt](https://github.com/klein0r/ioBroker.comfoairq/files/7607519/getuuid.txt)

Skript auf dem Server ablegen (als Python-Datei mit Endung .py - konnte ich hier leider nicht hochladen) und dann einfach mit "python3 getuuid.py" ausführen

**Comment by klein0r** [comment]
Achso, python. Ist ja wieder eine Dependency mehr. Ich gucke mal, wo ich das ablege. Danke für die Hilfe!

**Comment by Snapergy** [comment]
Ja, sorry :(

War froh es alleine hinbekommen zu haben :)
