### ISSUE TITLE
Value has type "number" but received "object"

### ISSUE THREAD

**Issue by Geg0r** [klein0r/ioBroker.comfoairq#18]
### The problem

Hi Matthias,

ich bekomme mit der aktuellen Adapter Version folgende Meldung

`
comfoairq.0 | 99401 | 2021-11-25 19:24:38.302 | info | State value to set for "comfoairq.0.sensor.fanNextChange" has to be type "number" but received type "object"
-- | -- | -- | -- | --
comfoairq.0 | 99401 | 2021-11-25 19:23:00.742 | info | State value to set for "comfoairq.0.version.gateway" has to be type "string" but received type "number"
comfoairq.0 | 99401 | 2021-11-25 19:23:00.685 | info | State value to set for "comfoairq.0.sensor.fanNextChange" has to be type "number" but received type "object"
comfoairq.0 | 99401 | 2021-11-25 19:23:00.678 | info | State value to set for "comfoairq.0.version.comfonet" has to be type "string" but received type "number"
comfoairq.0 | 99401 | 2021-11-25 19:23:00.475 | info | starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.comfoairq, node: v14.18.1, js-controller: 3.3.18
`

Ist nur Kosmetik. aber evtl kannst du das fixen?

### Version of ioBroker js-controller

3.3.18

### Version of Adapter

0.1.0

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Doppelt - siehe #12 

Instanz stoppen, alle Objekte löschen und dann wieder starten.

https://github.com/klein0r/ioBroker.comfoairq/commit/16c935fafb88f289454cb3bd6ca21d7070ba0ad8
