### ISSUE TITLE
PIN get lost

### ISSUE THREAD

**Issue by Streit187** [klein0r/ioBroker.comfoairq#19]
### The problem

After reboot of the Host the PIN get lost and has to retype in adapter config. 

### Version of ioBroker js-controller

5.1.25

### Version of Adapter

0.1.0

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
How to you reboot the instance? With scripts? Hopefully NOT like this:

```
var obj = getObject('system.adapter.comfoairq.0');
obj.common.enabled = false;
setObject('system.adapter.comfoairq.0', obj);
```

**Comment by Streit187** [comment]
No, not on restart of the instance but on reboot of the host. In my case a Pi.

**Comment by klein0r** [comment]
Please provide the version of the js-controller and nodejs

**Comment by Streit187** [comment]
JS-Controller: 3.3.21
NODE.JS: V12.22.1

**Comment by Streit187** [comment]
This is since the last adapter update to 0.1.0.  It is not critical. Would be interesting if there is someone else with same behavior.

**Comment by Streit187** [comment]
Since last iob update the error is gone.
