### ISSUE TITLE
No Connection to Comfoairq

### ISSUE THREAD

**Issue by raetsch** [klein0r/ioBroker.comfoairq#2]
The Adapter stays yellow and says comfoairq = false
IP-address is correct,
UUID is correct (should be, last part IS MAC-Address).
PIN is correct.

Here are the logs:

comfoairq.0 | 2020-09-23 21:43:53.336 | info | (26969) starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.comfoairq, node: v10.16.3
-- | -- | -- | --
comfoairq.0 | 2020-09-23 21:43:50.240 | info | (23707) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
comfoairq.0 | 2020-09-23 21:43:50.240 | info | (23707) terminating
comfoairq.0 | 2020-09-23 21:43:50.239 | info | (23707) Got terminate signal TERMINATE_YOURSELF

regards
raetsch

**Comment by klein0r** [comment]
This is currently under development - the current version is not working
