### ISSUE TITLE
Frage, was ist der Sensor 209 RMOT

### ISSUE THREAD

**Issue by DerDoubleD** [klein0r/ioBroker.comfoairq#21]
### The problem

Frage, was ist der Sensor 209 RMOT

### Version of nodejs

v14.18.2

### Version of ioBroker js-controller

3.3.22

### Version of Adapter

latest

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by Streit187** [comment]
RMOT = Running Mean Outdoor Temperature / Mittlere Betriebsaußentemperatur

**Comment by DerDoubleD** [comment]
Super, Danke für die schnelle Antwort!
