### ISSUE TITLE
UUID?

### ISSUE THREAD

**Issue by Streit187** [klein0r/ioBroker.comfoairq#5]
Hi, 
where can I find the UUID of ComfoConnect? 
Thank you
BR Streit

**Comment by klein0r** [comment]
1. Install the latest Version from GitHub (published 1 minute ago)
2. Start the instance without any configuration
3. Check the log file - should contain something like this:

```(3748) Device discovery finished: {"comfouuid":"00000000003410138001144fd71e24cc","comfoair":"172.16.0.248","port":56747}```

4. Copy those information in the instance configuration and try again

**Comment by Streit187** [comment]
I can see:
comfoairq.0 | 2021-02-11 16:32:57.802 | warn | (22136) Device information not configured - starting discovery
for 10 minutes without result. 
ComfoConnect is present in Netwotk and reachable. App is disconnected.

**Comment by klein0r** [comment]
This adapter is still under development and has alpha status.
Just finished the first version today.

Hard to say why your Comfo Connect isn't discovered.

**Comment by Streit187** [comment]
Oh yes  i know it is beta and i am very happy that there is someone who takes up this topic. 
Is there another possibility to find out the UUID of the comfoconnect?

**Comment by klein0r** [comment]
Ah, my problem is, that the broadcast address is still fixed to 172.16.255.255
Sorry - just forgot to make that part dynamic during my development and testing 😄 

I will publish pre-release 0.0.4 soon

**Comment by Streit187** [comment]
Would it be possible to "make that part dynamic" or describe another way to get the UUID? I would like to test a little bit ans maybe assist to get a release of this adapter.

**Comment by klein0r** [comment]
Check Version 0.0.4

1. configure the broadcast address for your network in the instance
2. start the instance
3. check the log for discovery result
4. copy uuid and IP address to instance configuration
5. select some sensor values
6. save configuration and start the instance

**no support for this version - still a pre-release**

**Comment by Streit187** [comment]
Perfect. This works so far. Do you want to know further errors or not in this early pre-release?

**Comment by klein0r** [comment]
Feel free to create issues for errors. But I also get some errors in some cases. Error handling currently is not implemented 😄

**Comment by Snapergy** [comment]
Hi,

i dont get any uuid. broadcast address is correct und wifi adapter is still available. i use iobroker with docker, could this bring some problems?

**Comment by Snapergy** [comment]
@klein0r any suggestions?

**Comment by klein0r** [comment]
@Snapergy Yes, since upnp requests don't work within the docker container (just in network mode host).

**Comment by Snapergy** [comment]
What can i do to get the uuid?

**Comment by Snapergy** [comment]
@klein0r keine andere Möglichkeit?

**Comment by Nexus1212** [comment]
Bei mir das selbe Prpblem. Ich bekomme keine UUID. Der IO-Broker läuft bei mir im Docker.

Kann man die UUID irgendwie anders erhalten?
