### ISSUE TITLE
Adpapter Terminated Without reason

### ISSUE THREAD

**Issue by KOS-CH** [klein0r/ioBroker.comfoairq#6]
Hi 
thanks for developing the adapter! 

The Adapter is Terminated after 15min with Log output: 

comfoairq.0	2021-02-19 09:31:48.709	info	(31411) Terminated (NO_ERROR): Without reason
comfoairq.0	2021-02-19 09:31:48.709	info	(31411) terminating
comfoairq.0	2021-02-19 09:31:48.706	error	at processTimers (internal/timers.js:497:7)
comfoairq.0	2021-02-19 09:31:48.706	error	at listOnTimeout (internal/timers.js:554:17)
comfoairq.0	2021-02-19 09:31:48.706	error	at ComfoAirQ._reconnect (/opt/iobroker/node_modules/comfoairq/lib/comfoconnect.js:190:75)
comfoairq.0	2021-02-19 09:31:48.706	error	(31411) TypeError: config.getTimestamp(...) is not a function
comfoairq.0	2021-02-19 09:31:48.706	error	(31411) uncaught exception: config.getTimestamp(...) is not a function

After 3-4 retries the Adapter goes back to green and "Verbunden mit comfoairq" is working again.

Have you an Idea what could the issue? 

Regards

**Comment by Streit187** [comment]
I`m getting the same error logs but 30 sec. after every adapter start and without any stable connection to comfair modul. 
After two restart i get "warn | Do not restart adapter system.adapter.comfoairq.0 because restart loop detected"

**Comment by lonestar2001** [comment]
Same here, Adapter is Not yet Running With my q350.  Looking forward for an update. Thanks for implementing.

**Comment by lonestar2001** [comment]
Hier die genaue Ausgabe:
<html><head></head><body>

host.buanet-iobroker3 | 2021-07-01 15:48:44.985 | error | instance system.adapter.comfoairq.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
comfoairq.0 | 2021-07-01 15:48:44.452 | warn | (24150) Terminated (UNCAUGHT_EXCEPTION): Without reason
comfoairq.0 | 2021-07-01 15:48:44.451 | info | (24150) terminating
comfoairq.0 | 2021-07-01 15:48:44.445 | error | (24150) config.getTimestamp(...) is not a function
comfoairq.0 | 2021-07-01 15:48:44.445 | error | (24150) TypeError: config.getTimestamp(...) is not a function     at ComfoAirQ._reconnect (/opt/iobroker/node_modules/comfoairq/lib/comfoconnect.js:190:75)     at listOnTimeout (internal/timers.js:554
comfoairq.0 | 2021-07-01 15:48:44.444 | error | (24150) uncaught exception: config.getTimestamp(...) is not a function
comfoairq.0 | 2021-07-01 15:48:44.442 | error | (24150) undefined
comfoairq.0 | 2021-07-01 15:48:44.442 | error | (24150) unhandled promise rejection: undefined
comfoairq.0 | 2021-07-01 15:48:44.441 | error | (24150)  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
comfoairq.0 | 2021-07-01 15:48:29.341 | info | (24150) starting. Version 0.0.4 in /opt/iobroker/node_modules/iobroker.comfoairq, node: v12.22.1, js-controller: 3.2.16

</body></html>
