### ISSUE TITLE
Kann keine Verbindung herstellen

### ISSUE THREAD

**Issue by axelhannemann** [klein0r/ioBroker.comfoairq#7]
Hallo,

vielen Dank für den Adapter, auf sowas habe ich schon länger gewartet. Leider habe ich aktuell das Problem, dass ich nach erfolgreicher Installation mit der Konfiguration nicht ganz klar komme. Die Broadcast Address bezieht sich auch die Adresse des Netzwerk routers oder des Geräts auf dem IOBroker läuft? Außerdem würde ich gerne wissen ob die UUID frei wählbar ist oder wo ich die ablesen kann? Die Instanz im IOBroker bleibt "gelb": Verbunden mit Host und Lebenszeichen sind mit wahr gekennzeichnet, allerdings bleibt Verbunden mit comfoairq auf falsch.

Mit freundlichen Grüßen
Axel Hannemann

**Comment by axelhannemann** [comment]
Hallo nochmal,

Hier das log dazu:

comfoairq.0 | 2021-02-28 15:39:53.294 | error | at Timer.processTimers (timers.js:223:10)
-- | -- | -- | --
comfoairq.0 | 2021-02-28 15:39:53.294 | error | at listOnTimeout (timers.js:263:5)
comfoairq.0 | 2021-02-28 15:39:53.294 | error | at tryOnTimeout (timers.js:300:5)
comfoairq.0 | 2021-02-28 15:39:53.294 | error | at ontimeout (timers.js:436:11)
comfoairq.0 | 2021-02-28 15:39:53.294 | error | at ComfoAirQ._reconnect (/opt/iobroker/node_modules/comfoairq/lib/comfoconnect.js:190:75)
comfoairq.0 | 2021-02-28 15:39:53.294 | error | (13955) TypeError: config.getTimestamp(...) is not a function
comfoairq.0 | 2021-02-28 15:39:53.293 | error | (13955) uncaught exception: config.getTimestamp(...) is not a function
comfoairq.0 | 2021-02-28 15:39:53.263 | error | (13955) unhandled promise rejection: undefined
Unhandled | 2021-02-28 15:39:53.262 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by Streit187** [comment]
Die Broadcast Adresse bezieht sich auf dein Netzwerk. Wenn dein Router z.B. 192.168.178.1 hat dann ist deine Broadcast Adresse 192.168.178.255. 
Wenn du diese und den Port eingetragen hast und den Adapter startest solltest du im Log die nicht(!) wählbare UUID finden.

**Comment by axelhannemann** [comment]
Vielen Dank, hat funktioniert, kann erst mal alle Werte auslesen. Thx für die kompetente Unterstützung
