### ISSUE TITLE
Gesamtenergieverbrauch "steht"

### ISSUE THREAD

**Issue by Geg0r** [klein0r/ioBroker.comfoairq#72]
### The problem

Hi Matthias,

nicht wirklich ein Problem mit dem Adapter (vermutlich), aber in der Zehnder App steht der Energieverbrauch (gesamt seit Jahresbeginn und Gesamt seit Beginn) seit einigen Monaten bei mir...
Gerät: ComfoAir Q600 D ST

Der aktuelle Verbrauch wird weiterhin aktualisiert, ebenso wie alle anderen Werte.

Ist das bei dir auch so?

### Version of nodejs

16.18.1

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

0.2.0

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Schwer zu sagen, warum man dafür keine Events bekommt. Ich nutze den Adapter ja aktuell auch gar nicht mehr 😞

**Comment by timtaylorrr** [comment]
Hallo Matthias, 

nutzt Du einen anderen Adapter für die Lüftungsanlage? Ich würde gerne etwas mehr machen als das, was mir die App bietet. 

Danke und Grüße
Holger

**Comment by klein0r** [comment]
@timtaylorrr https://produkte.zehnder-systems.de/de/produkt/zehnder-comfoconnect-knx-c

**Comment by klein0r** [comment]
Kann das Verhalten leider nicht reproduzieren
