### ISSUE TITLE
Vorschlag: OneButtonCommand

### ISSUE THREAD

**Issue by Streit187** [klein0r/ioBroker.comfoairq#8]
Für die Steuerung wäre es gut einzelne Datenpunkte pro Funktion zu haben. Bedeutet:
- Fanboost: values 10/20/30/Off
- Bypass: values On/Auto/Off
- Fanmode: values Away/Low/Medium/High
- Mode: Auto/Manual
- TempProf: Cool/Normal/Warm
- VentMode: Balance/Supply

**Comment by klein0r** [comment]
Gerne per Pull-Request einreichen. Macht die Implementierung und das Error-Handling deutlich komplexer.

**Comment by Streit187** [comment]
Keinen Stress deswegen. Mache es erst einmal über ein Skript.
